baseURL = 'https://ruubby.com'
locale = 'en-us'
title = 'Ruubby'
theme = "PaperMod"
copyright = "© 2026 Ruubby. All Rights Reserved."

[params]
  defaultTheme = "auto"   # auto | light | dark
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowPostThumbnailInList = true
  

[menu]

  [[menu.main]]
    name = "In Stock"
    url = "/tags/in-stock/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 15
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 25

[outputs]
  home = ["HTML", "RSS", "JSON"]
